# Generated by Django 5.0.1 on 2024-02-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='Book_Name',
        ),
        migrations.RemoveField(
            model_name='every_day',
            name='Book_Name',
        ),
        migrations.DeleteModel(
            name='CkeckDetails',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='IssueBook',
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
        migrations.DeleteModel(
            name='Every_day',
        ),
    ]
