# Generated by Django 5.0.1 on 2024-02-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('las_app', '0002_remove_issuebook_book_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Author', models.CharField(blank=True, max_length=100, null=True)),
                ('DOP', models.DateField(max_length=50)),
                ('Condition', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CkeckDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('DOJ', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Every_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Book_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='las_app.bookdetails')),
            ],
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Stu_Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Section', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Issue_Date', models.DateField()),
                ('Till_Date', models.DateField()),
                ('Charge', models.IntegerField(blank=True, null=True)),
                ('Condition', models.IntegerField()),
                ('Request_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('Request_genrated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Book_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='las_app.bookdetails')),
            ],
        ),
    ]
