# Generated by Django 5.0.1 on 2024-02-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='Section',
        ),
    ]
