# Generated by Django 5.0.1 on 2024-02-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0005_remove_issuebook_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='Request_genrated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='Section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
