# Generated by Django 5.0.1 on 2024-02-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0007_remove_issuebook_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
