# Generated by Django 5.0.1 on 2024-02-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0008_issuebook_charge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueBook',
        ),
    ]
