# Generated by Django 5.0.1 on 2024-02-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0009_delete_issuebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Stu_Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Section', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Issue_Date', models.DateField()),
                ('Till_Date', models.DateField()),
                ('Charge', models.IntegerField(blank=True, null=True)),
                ('Condition', models.IntegerField()),
                ('Request_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('Request_genrated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Book_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='las_app.bookdetails')),
            ],
        ),
    ]
