# Generated by Django 5.0.1 on 2024-02-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0012_bookdetails_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='Book_Name',
            new_name='Book',
        ),
    ]
