# Generated by Django 5.0.1 on 2024-02-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0014_alter_issuebook_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='Request_genrated_by',
        ),
    ]
