# Generated by Django 5.0.1 on 2024-02-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0016_issuebook_request_genrated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='Book_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='las_app.bookdetails'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='Issue_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='Till_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
