# Generated by Django 5.0.1 on 2024-02-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0017_alter_issuebook_book_name_alter_issuebook_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='fk_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='las_app.userdetails'),
        ),
    ]
