# Generated by Django 5.0.1 on 2024-02-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0018_issuebook_fk_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Stu_Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Section', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Issue_Time', models.DateField(blank=True, null=True)),
                ('Till_Time', models.DateField(blank=True, null=True)),
                ('Time_Period', models.DateField(blank=True, null=True)),
                ('Charge', models.IntegerField(blank=True, null=True)),
                ('Condition', models.CharField(blank=True, max_length=100, null=True)),
                ('Request_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('Request_genrated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Book_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='las_app.bookdetails')),
                ('fk_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='las_app.userdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Every_day',
        ),
    ]
