# Generated by Django 5.0.1 on 2024-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0019_daily_visitors_delete_every_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_visitors',
            name='Issue_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_visitors',
            name='Till_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_visitors',
            name='Time_Period',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
