# Generated by Django 5.0.1 on 2024-02-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0021_rename_price_bookdetails_per_day_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_visitors',
            old_name='Request_Status',
            new_name='Return_Book',
        ),
        migrations.RemoveField(
            model_name='daily_visitors',
            name='Time_Period',
        ),
        migrations.RemoveField(
            model_name='daily_visitors',
            name='img',
        ),
    ]
