# Generated by Django 5.0.1 on 2024-03-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_app', '0023_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
